simulation:
  xml_path: "ballmove.xml"
  site_name: "ee_site"
  dt: 0.002
  keys_file_path: "./keys.env"
  base_dir: "./Results/"
  move_csv_path: "./Results/logs/move.csv"
  max_iters: 400

robot:
  joint_names: ["shoulder_pan", "shoulder_lift", "elbow", "wrist_1", "wrist_2", "wrist_3"]
  home_joint_positions: [0.16986918, -2.09439510, -1.1, -0.34906585, 1.57079632, 1.64722557]
  mop_z_height: 0.49

ik_params:
  init_lambda: 0.15
  tol: 0.001
  step_clip: 0.2
  max_wp_step: 0.03
  max_iters_per_wp: 300
  print_every: 60
  ik_max_iters: 50

dmp_params:
  n_bfs: 10
  num_balls: 150
  num_x_segments: 3
  num_y_segments: 2
  step_size: 100
  random_scale: 10.0
  deci_build: 2

animation:
  duration: 4.0
  fps: 75

llm_settings:
  gemini_model: "gemini-2.5-flash"
  ollama_model: "gpt-oss:120b"
  history_window: 25
  trajectory_history_window: 40
  feedback_window: 30
  n_warmup: 20
  seed_number: 42
  traj_in_prompt: True

obstacle_params:
  rect_d0: 0.05
  rect_eta: 25.0
  obs_d0: 0.1
  obs_eta: 25.0
  max_force: 220.0





cmaes_settings:
  sigma0: 10.0         
  pop_size: 14         
  seed: 42              
  save_best_only: True  
  run_type: "cmaes-optimization" 
